site_name: My Docs

theme:
  name: material
  features:
    - content.tabs.link
    - navigation.tabs
    - toc.integrate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

nav:
  - index.md
  - quickstart.md
  - Guides:
    - how-to.md
    - tutorial.md
    - explanation.md
  - examples.md
  - reference.md